---
title: "binscatter"
author: "Austin Kennedy"
date: "11/11/2022"
output: html_document
---

```{r Clear memory and setup}
rm(list=ls())
options(scipen=999)
```

```{r Packages}
library(tidyverse)
library(ggplot2)
source("../temporary/stat_binscatter.R")
library(data.table)
```
```{r Load Data}
data <- read.csv('../temporary/volumes_opt_industry.csv')
```




```{r Create Bins}
start <- 1500
end <- 1900
interval <- 25

breaks <- seq(start, end, by = interval)
tags <- seq(start, end - 25, by = interval)
label <- sprintf(paste0(tags, "-", tags+(interval - 1)))
```

```{r bin volumes}
bins <- cut(data$Year_rounded,
            breaks = breaks,
            include.lowest = TRUE,
            right = FALSE,
            labels = label
            )

data$year_group <- factor(bins,
                     levels = label,
                     ordered = TRUE)
```

```{r Bin Scatter Plots}

for (i in label){
  df <- data %>% filter(year_group == i)
  
  fig <- ggplot(df, aes(x = industry_percentile, y = optimism_percentile)) +
    # geom_point(alpha = .1) +
    geom_smooth(method = "lm", formula = y~poly(x,2), se = FALSE) +
    xlim(0,1) +
    # ylim(0.25,0.7) +
    stat_binscatter(color = "red", geom = "pointrange") +
    labs(title = i, x = "Industry (Percentile)", y = "Optimism (Percentile)") +
    theme_bw()
  
  
  show(fig)
  path <- sprintf('../output/bin_scatters/%s.png', i)
  ggsave(path)
}
```

```{r Plots with volumes}
for (i in label){
  df <- data %>% filter(year_group == i)
  
  fig <- ggplot(df, aes(x = industry_percentile, y = optimism_percentile)) +
    geom_point(alpha = .1, size = 1) +
    geom_smooth(method = "lm", formula = y~poly(x,2), se = FALSE) +
    # xlim(0,1) +
    # ylim(-0.1,0.1) +
    stat_binscatter(color = "red", geom = "pointrange") +
    labs(title = i, x = "Industry (Percentile)", y = "Optimism (Percentile)") +
    theme_bw()
  
  
  show(fig)
  path <- sprintf('../output/bin_scatters/with_points/%s.png', i)
  ggsave(path)
}

```


```{r Count unique}
length(which(data$Optimism == 0))
```






















