---
title: "econometrics_industrialization"
author: "Austin Kennedy"
date: "11/15/2022"
output: html_document
---

```{r Clear memory and setup}
rm(list=ls())
options(scipen=999)
```

```{r Load Packages}

library(tidyverse)
library(fixest)
library(data.table)
library(broom)
library(modelsummary)
library(msm)
library(ggpubr)
library(reshape2)
library(kableExtra)

```


```{r Load Data}
volumes <- read.csv('../temporary/volumes_opt_industry.csv')
```

```{r Clean up}
volumes <- volumes[,-1] #Drops 'X' which is just the index attached by Python
```

```{r Create years and bins}
years <- seq(1510,1890, by=1)
bins <- seq(1510, 1890, by = 20)
```

```{r Assign volumes to bins}
volumes <- volumes[volumes$Year_rounded >= (min(bins) - 10),]
#Merge volume years to closest bin
a = data.table(Value=volumes$Year_rounded) #Extract years
a[,merge:=Value] #Give data.table something to merge on
b = data.table(Value = bins)
b[,merge:=Value]
setkeyv(a, c('merge')) #Sort for quicker merge
setkeyv(b, c('merge'))
rounded = b[a, roll='nearest'] #Merge to nearest
rounded <- distinct(rounded) #Get distinct values for easier merge to 'volumes'
# volumes <- data.table(volumes)
volumes <- merge(volumes, rounded, by.x = "Year_rounded", by.y = "merge")
#Remove unnecessary column
volumes <- volumes %>%
  subset(select = -c(i.Value)) %>%
  rename(bin = Value)
```


```{r Regressions}
mod1 <- volumes %>% group_by(bin) %>%
  do(x = lm(optimism_percentile ~ Science*Religion*industry_percentile + Science*Political.Economy*industry_percentile + Religion*Political.Economy*industry_percentile - Religion, data = .))

#
# mod <- feols(optimism_percentile ~ Science + Political.Economy + Science*Political.Economy + Science*Religion + Religion*Political.Economy + i(bin, Science, 1610) + i(bin, Religion, 1610) + i(bin, Political.Economy, 1610) + i(bin, Science*Religion, 1610) + i(bin, Science*Political.Economy, 1610) + i(bin, Political.Economy*Religion, 1610) | bin, data = volumes)

#drop obs before 1610 bin
volumes_1 <- volumes %>%
  filter(bin >= 1610)

mod <- feols(optimism_percentile ~ Science + Political.Economy + Science*Political.Economy + Science*Religion + Religion*Political.Economy + i(bin, Science, 1610) + i(bin, Political.Economy, 1610) + i(bin, Science*Religion, 1610) + i(bin, Science*Political.Economy, 1610) + i(bin, Political.Economy*Religion, 1610) + i(bin, ref = 1610) - Religion, data = volumes_1)

mod_no_interactions <- feols(optimism_percentile ~ Science + Political.Economy + Science*Political.Economy + Science*Religion + Religion*Political.Economy + i(bin, ref = 1610) - Religion, data = volumes_1)

# mod <- feols(optimism_percentile ~ Science + Political.Economy + Science*Political.Economy + Science*Religion + Religion*Political.Economy + i(bin, Science) + i(bin, Political.Economy) + i(bin, Science*Religion) + i(bin, Science*Political.Economy) + i(bin, Political.Economy*Religion) + i(bin), data = volumes)

etable(mod_no_interactions)
```
```{r Group results by year and variable}
estimates <- tibble::rownames_to_column(mod$coeftable, "coefficient")

#parse variable names into FEs and dep vars


estimates <- estimates %>%
  mutate(coefficient = str_remove(coefficient, "bin::")) %>%
  mutate(coefficient = str_replace(coefficient, '^([^0-9:]*):([^0-9:]*)$', '\\1 * \\2')) %>% #Format interactions correctly
  mutate(split = strsplit(coefficient, ':')) %>%
  mutate(year = sapply(split, function(x) x[1]),
         variable = ifelse(sapply(split, length) == 2, sapply(split, function(x) x[2]), sapply(split, function(x) x[1]))) %>% #assign years and variables to correct columns
  select(-split)

estimates <- estimates %>%
  mutate(variable = ifelse(is.na(as.numeric(variable)), variable, "(Intercept)")) %>%
  mutate(year = ifelse(is.na(as.numeric(year)), 'Reference', year))



# estimates <- estimates %>%
#   mutate(coefficient = str_remove(coefficient, "bin::")) %>%
#   mutate(split = strsplit(coefficient, ':')) %>%
#   mutate(year = ifelse(sapply(split, length) == 2, sapply(split, function(x) x[1]), '0'),
#          variable = ifelse(sapply(split, length) == 2, sapply(split, function(x) x[2]), sapply(split, function(x) x[1]))) %>%
#   select(-split)
# 
# estimates <- estimates %>%
#   mutate(variable = ifelse(is.na(as.numeric(year)), paste(year, variable, sep = ' * '), variable)) %>%
#   mutate(year = ifelse(is.na(as.numeric(year)), '0', year))


# estimates <- estimates %>%
#   mutate(coefficient = str_remove(coefficient, "bin::")) %>%
#   separate_wider_delim(col = coefficient, into = c("year", "variable"), sep = "^(\\d{4}):([a-zA-Z]+)$|^([a-zA-Z]+):(\\d{4})$|^([a-zA-Z]+):([a-zA-Z]+)$", remove = FALSE, convert = TRUE, names = c("year", "variable", NA, NA, "variable", "variable"))

# # If 'firstword' is not a number, move it to the 'secondword' column along with the original 'secondword' string
# df <- df %>%
#   mutate(secondword = ifelse(is.na(as.numeric(firstword)), paste(firstword, secondword, sep = ":"), secondword))
# 
# # Keep only the rows where 'firstword' is a number
# df <- df %>%
#   filter(!is.na(as.numeric(firstword)))

estimates
```

```{r Reshape coefficients and std errors into dfs}
#variables as rows and years as columns
coefs <- dcast(estimates, variable ~ year, value.var = "Estimate")
coefs <- coefs %>%
  relocate("Reference", .after = "variable") %>%
  arrange(str_length(variable), variable) %>%
  arrange(variable != "(Intercept)")

std_errs <- dcast(estimates, variable ~ year, value.var = "Std. Error")
std_errs <- std_errs %>%
  relocate("Reference", .after = "variable") %>%
  arrange(str_length(variable), variable) %>%
  arrange(variable != "(Intercept)")


```

```{r Get output into models to be compatible with modelsummary}
models <- list()

for (i in 2:ncol(coefs)){

model <- list()

class(model) <- "custom"

tidy.custom <- function(x, ...) {
  data.frame(
    term = coefs$variable,
    estimate = coefs[[i]],
    std.error = std_errs[[i]]
  )
}

if (i == 2) {

glance.custom <- function(x, ...) {
  data.frame(
    "nobs" = mod$nobs
  )
}
} else{
  glance.custom <- function(x, ...) {
    data.frame(
      "nobs" = " "
    )
  }
}
models[[colnames(coefs)[[i]]]] <- modelsummary(model, output = "modelsummary_list")
}

```
```{r ModelSummary Tables}

```

```{r KableExtra tables}
kbl(coefs, booktabs = T)
```

```{r Raw FE regression output}
modelsummary(mod_no_interactions,
             stars = TRUE,
             output = "../output/optimism_results_no_interactions.txt")
```


```{r Extract results}
models <- list()

for (i in 1:length(bins)){
    mod_tmp <- mod1$x[[i]] #capture models for output table
    models[[toString(bins[[i]])]] <- mod_tmp
}

```

```{r Output Tables}

# omit <- c("(Intercept)|Science|industry_percentile|Political.Economy|Science:Religion|Science:industry_percentile|Religion:industry_percentile|Science:Political.Economy|Religion:Political.Economy")

omit <- c("(Intercept)|Science:Religion")

rename <- c("Political.Economy" = "PolitEcon", "industry_percentile" = "Industry",
            "Science:Religion" = "$\\text{Science} \\times \\text{Religion}$", "Science:industry_percentile" = "$\\text{Science} \\times \\text{Industry}$", "Religion:industry_percentile" = "$\\text{Religion} \\times \\text{Industry}$", "Science:Political.Economy" = "$\\text{Science} \\times \\text{PolitEcon}$", "Religion:Political.Economy" = "$\\text{Religion} \\times \\text{PolitEcon}$", "Science:Religion:industry_percentile" = "$\\text{Science} \\times \\text{Religion} \\times \\text{Industry}$", "Science:industry_percentile:Political.Economy" = "$\\text{Science} \\times \\text{PolitEcon} \\times \\text{Industry}$", "Religion:industry_percentile:Political.Economy" = "$\\text{Religion} \\times \\text{PolitEcon} \\times \\text{Industry}$")

cm <- c("Science:Religion:industry_percentile" = "$\\text{Science} \\times \\text{Religion} \\times \\text{Industry}$", "Science:industry_percentile:Political.Economy" = "$\\text{Science} \\times \\text{PolitEcon} \\times \\text{Industry}$", "Religion:industry_percentile:Political.Economy" = "$\\text{Religion} \\times \\text{PolitEcon} \\times \\text{Industry}$")

# modelsummary(models[1:8],
#              stars = TRUE,
#              gof_omit = "R2 Within|R2 P|Log|AIC|BIC|RMSE",
#              coef_map = cm,
#              title = "Dependent Variable: Optimism Percentile",
#              escape = FALSE,
#              threeparttable=TRUE,
#              output="../output/mod1_1.tex"
#              )
#
# modelsummary(models[9:15],
#              stars = TRUE,
#              gof_omit = "R2 Within|R2 P|Log|AIC|BIC|RMSE",
#              coef_map = cm,
#              title = "Dependent Variable: Optimism Percentile",
#              escape = FALSE,
#              threeparttable = TRUE,
#              notes = "All lower-order interactions and independent variables included. Regressions are binned for every 20 years (+/-) 10 years. Standard errors in parenthesis.",
#              output="../output/mod1_2.tex"
#              )


modelsummary(models[1:8],
             stars = TRUE,
             gof_omit = "R2 Within|R2 P|Log|AIC|BIC|RMSE",
             coef_rename = rename,
             title = "Dependent Variable: Optimism Percentile",
             escape = FALSE,
             threeparttable=TRUE,
             output="../output/mod1_1.tex"
             )

modelsummary(models[9:15],
             stars = TRUE,
             gof_omit = "R2 Within|R2 P|Log|AIC|BIC|RMSE",
             coef_rename = rename,
             title = "Dependent Variable: Optimism Percentile",
             escape = FALSE,
             threeparttable = TRUE,
             notes = "All lower-order interactions and independent variables included. Regressions are binned for every 20 years (+/-) 10 years. Standard errors in parenthesis.",
             output="../output/mod1_2.tex"
             )


```


```{r ChatGPT snippets}
# If 'firstword' is not a number, move it to the 'secondword' column along with the original 'secondword' string
df <- df %>%
  mutate(secondword = ifelse(is.na(as.numeric(firstword)), paste(firstword, secondword, sep = ":"), secondword))

# Keep only the rows where 'firstword' is a number
df <- df %>%
  filter(!is.na(as.numeric(firstword)))

# Load the reshape2 package
library(reshape2)

# Create a new data frame with 'firstword' as the columns and 'secondword' as the rows
df_new <- dcast(df, secondword ~ firstword, value.var = "data")
```

```{r Code Playground}
models <- list()



model <- list()

class(model) <- "custom"

tidy.custom <- function(x, ...) {
  data.frame(
    term = coefs$variable,
    estimate = coefs[[2]],
    std.error = std_errs[[2]]
  )
}


glance.custom <- function(x, ...) {
  data.frame(
    "nobs" = mod$nobs
  )
}

modelsummary(model)

```



